DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
    PHONE_NUMBER BIGINT NOT NULL PRIMARY KEY,
    ZIPCODE VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    STREET_ADDRESS VARCHAR(255)
);