DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
    PHONE_NUMBER BIGINT NOT NULL PRIMARY KEY,
    ZIPCODE VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    STREET_ADDRESS VARCHAR(255)
);
DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT(
    PRODUCT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL
);
